name: sensitive_clipboard_example
description: Demonstrates how to use the sensitive_clipboard plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.3 <3.0.0"
  flutter: "2.0.6"

dependencies:
  flutter:
    sdk: flutter

  sensitive_clipboard:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true