name: sensitive_clipboard
description: Flutter plugin that wraps the original flutter clipboard and allows hide sensitive content
version: 0.0.2
homepage: https://github.com/marcellocamara/sensitive_clipboard

environment:
  sdk: ">=2.12.3 <3.0.0"
  flutter: ">=2.0.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: marcello.dev.sensitive_clipboard
        pluginClass: SensitiveClipboardPlugin
      ios:
        pluginClass: SensitiveClipboardPlugin
